Repository sruti2024/PRO_Act, pull requests merged in 2021-05, with the labels that each got.

#191 Modified the variable names
  home/views.py
Labels: gssoc21

#194 Renamed : kebab-case filename to snake_case
  home/views.py
  static/js/reset_pwd.js
  templates/forgot_password.html
Labels: Level0, gssoc21

#198 added darkmode to website
  static/css/base.css
  static/css/moduleStyle.css
  static/js/darkmode.js
  templates/base.html
  templates/contact.html
  templates/index.html
  templates/modules.html
  templates/profile.html
  templates/project_add.html
  templates/project_view.html
Labels: Level3, enhancement, gssoc21

#201 [clean] : Remove Redundant Comments & Format
  home/admin.py
  home/templatetags/format_datetime.py
  home/views.py
  static/css/changepassword.css
  static/css/index.css
  static/css/profile.css
  static/css/welcome.css
  templates/404.html
  templates/about.html
  templates/index.html
  templates/modules.html
  templates/signup.html
Labels: Level0, gssoc21

#205 [Fix] : Social auths and Added Github OAuth
  .env
  db.sqlite3
  home/__pycache__/admin.cpython-38.pyc
  home/__pycache__/apps.cpython-38.pyc
  home/__pycache__/models.cpython-38.pyc
  home/__pycache__/urls.cpython-38.pyc
  home/__pycache__/views.cpython-38.pyc
  pro_act/__pycache__/settings.cpython-38.pyc
  pro_act/__pycache__/urls.cpython-38.pyc
  pro_act/__pycache__/wsgi.cpython-38.pyc
  pro_act/settings.py
  requirements.txt
  static/css/login.css
  static/css/signup.css
  templates/login.html
  templates/signup.html
Labels: Level3, gssoc21
