Repository sruti2024/PRO_Act, pull requests merged in 2021-04, with the labels that each got.

#105 Login issues sorted
  .vscode/settings.json
  db.sqlite3
  home/views.py
  pro_act/__pycache__/settings.cpython-37.pyc
  pro_act/__pycache__/urls.cpython-37.pyc
  pro_act/__pycache__/wsgi.cpython-37.pyc
Labels: Level1, gssoc21

#107 Enhance Index CSS
  db.sqlite3
  home/views.py
  requirements.txt
  static/images/add.png
  static/images/module.png
  static/images/timer.png
  static/images/update.png
  templates/about.html
  templates/base.html
  templates/index.html
Labels: Level2, gssoc21

#108 the logo is placed in a folder called logo<images<static folders.
  static/Pro_Act_Logo/ProAct logo.svg
  static/images/logo/PRO_ACT_Bck.svg
Labels: Level0, gssoc21

#126 spell check in readme.md
  README.md
Labels: Level0, documentation, easy, gssoc21

#127 [GSSOC' 21] [ENHANCEMENT] re-designed login in with google button
  templates/login.html
  templates/signup.html
Labels: CSS, Frontend, Level2, enhancement, gssoc21

#123 added functionality of subtasks
  .vscode/settings.json
  db.sqlite3
  home/admin.py
  home/migrations/0001_initial.py
  home/migrations/0002_subtask.py
  home/migrations/0003_project_add_proj_image.py
  home/migrations/__init__.py
  home/models.py
  home/urls.py
  home/views.py
  pro_act/__pycache__/settings.cpython-37.pyc
  pro_act/__pycache__/urls.cpython-37.pyc
  pro_act/__pycache__/wsgi.cpython-37.pyc
  static/css/moduleStyle.css
  templates/modules.html
Labels: Level3, gssoc21

#139 add whatsapp in footer
  templates/base.html
Labels: Level1, gssoc21

#140 Activated Welcome Bot
  .github/workflows/greetings.yml
Labels: Level0, gssoc21

#145 fixed forgot password page's bug
  templates/forgot-password.html
Labels: Level0, gssoc21

#162 deps : Add pandas in requirements.txt
  requirements.txt
Labels: Level0, gssoc21

#177 Added 404 error handler
  home/views.py
  pro_act/urls.py
  templates/404.html
Labels: Level3, gssoc21
